### ISSUE TITLE
std::make_shared issue

### ISSUE THREAD

**Issue by Lhyshining** [lturing/ORB_SLAM3_RGBD_PCL#1]
in src/PointCloudMapping.cc, 'std::make_shared' should be modified to 'boost::make_shared'

**Comment by lturing** [comment]
you are right, another way is:
git clone https://github.com/lturing/ORB_SLAM3_RGBD_PCL.git 
cd ORB_SLAM3_RGBD_PCL 
sed -i 's/++14/++17/g' CMakeLists.txt

std::make_shared is introduced in c++17

**Comment by Lhyshining** [comment]
> you are right, another way is: git clone https://github.com/lturing/ORB_SLAM3_RGBD_PCL.git cd ORB_SLAM3_RGBD_PCL sed -i 's/++14/++17/g' CMakeLists.txt
> 
> std::make_shared is introduced in c++17

Thanks for your reply, and thanks for your masterpiece work.
